### ISSUE TITLE
A SessionController was used after being disposed.

### ISSUE THREAD

**Issue by mohit41999** [AgoraIO-Community/Flutter-UIKit#52]
Once you have called dispose() on a SessionController, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:114:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:120:6)
#2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:233:12)
#3      _ValueListenableBuilderState.dispose (package:flutter/src/widgets/value_listenable_builder.dart:177:28)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4895:11)
#5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1883:13)
#6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#10     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#25     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6297:16)
#26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#31     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#36     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#37     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#38     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#39     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#40     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#41     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#42     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#44     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#45     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#46     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6297:16)
#47     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#48     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#50     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#51     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#53     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#54     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#56     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#57     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#58     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#59     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#60     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#61     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#62     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#63     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#64     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#65     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#66     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#67     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#68     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#69     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#70     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#71     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#72     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#73     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#74     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#75     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#77     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#78     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#79     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#80     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#81     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#82     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#83     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#84     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#85     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#86     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#87     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#88     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#89     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#90     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#91     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#92     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#93     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#94     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#95     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#96     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#97     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#98     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#99     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#100    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#101    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#102    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#103    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#104    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#105    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#106    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#107    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#108    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#109    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#110    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#111    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#112    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#113    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#114    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#115    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#116    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#117    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#118    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#119    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#120    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#121    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#122    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#123    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#124    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#125    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#126    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#127    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#128    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#129    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#130    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#131    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#132    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#133    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#134    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#135    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#136    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#137    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#138    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#139    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#140    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#141    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#142    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#143    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#144    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#145    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#146    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#147    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#148    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#149    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#150    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#151    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#152    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#153    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#154    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#155    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#156    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#157    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#158    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#159    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#160    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#161    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#162    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#163    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#164    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#165    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#166    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
#167    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#168    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#169    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#170    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#171    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#172    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#173    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#174    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
#175    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
#176    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
#177    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#178    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1892:25)
#179    BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2879:27)
#180    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2510:15)
#181    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2878:7)
#182    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:19)
#183    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#184    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#185    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#186    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#190    _invoke (dart:ui/hooks.dart:166:10)
#191    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#192    _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)

**Comment by khlewesamer** [comment]
after i comment this line 
    //widget.client.sessionController.dispose();
in AgoraVideoViewer file that solve the bug , mybe sessionController disoposied before this line ,
if this solve problim pls do new push

**Comment by khlewesamer** [comment]
the black screen is still there but I work around it by adding my one end button and passing it in extraButtons

**Comment by Meherdeep** [comment]
@mohit41999 The black screen that you mentioned occurs because there is no other screen in the navigation stack. So when you end the call `Navigator.pop(context)` pushes it to an empty screen.

**Comment by deShodhan** [comment]
Did you resolve the problem? You get the blank screen when you do not initialize agora properly. I resolved the blank screen but the sessionController error still exists.

**Comment by deShodhan** [comment]
> This above error occurs whenever i press disconnect button and after that black screen occurs

Did you resolve the problem? You get the blank screen when you do not initialize agora properly. I resolved the blank screen but the sessionController error still exists.

**Comment by khlewesamer** [comment]
I resolve sessionController problem by disable default end call button then add my own in extraButton , the problem comes from tring to disposed controller after widget gone

**Comment by dev-justine** [comment]
@khlewesamer 

I still have the same issue, can you please, show your code to end the call?

**Comment by dev-justine** [comment]
> after i comment this line //widget.client.sessionController.dispose(); in AgoraVideoViewer file that solve the bug , mybe sessionController disoposied before this line , if this solve problim pls do new push

This is my custom function to end the call
  void endConsultation(context) async{
    await client.sessionController.endCall();
    Navigator.pop(context);
  }    

But, I still get the error: a sessionController was used after being disposed.

I also get the error when I just pop the video call screen to a previous screen, without disposing any controller.

**Comment by khlewesamer** [comment]
```
extraButtons: [
                            FloatingActionButton(
                                backgroundColor: Colors.red,
                                child: Icon(Icons.call_end),
                                onPressed: () => _endMeating(context))
                          ],
                          enabledButtons: [
                            
                            BuiltInButtons.toggleCamera,
                            BuiltInButtons.toggleMic
                          ],
```

```
_endMeating(){
await client.sessionController.endCall();
Navigator.pop(context);

}
```
don't forget to comment on that line in AgoraVideoViewer file 

last thing after edit AgoraVideoViewer file u need rerun the app

**Comment by dev-justine** [comment]
@khlewesamer I did same thing you mentioned, but i kept on getting that same error.
`A SessionController was used after being disposed.`

**Comment by mohit41999** [comment]
@Meherdeep @khlewesamer  .. sorry for the late reply ..yes i got it solved by the same method suggested by you both .. thank you for the help.

**Comment by kairakhatri** [comment]
> @khlewesamer I did same thing you mentioned, but i kept on getting that same error. `A SessionController was used after being disposed.`

Did you fix it?😶

**Comment by alimajid124** [comment]
how we can do while using Adora UI Kit

**Comment by waqadArshad** [comment]
The same thing, even after putting my custom button and calling:

```
await client.sessionController.endCall();
```

I am still getting the error: `SessionController was used after being disposed.`

**Comment by waqadArshad** [comment]
> @Ascenio @hxingpax @Meherdeep @tadaspetra @maxxfrazer The same thing, even after putting my custom button and calling:
> 
> ```
> await client.sessionController.endCall();
> ```
> 
> I am still getting the error: `SessionController was used after being disposed.`

@khlewesamer @Meherdeep @deShodhan @mohit41999 does anyone have any real solution for this. and why isn't this fixed in the package itself?
Thanks

**Comment by maxxfrazer** [comment]
@Meherdeep could you take a look at this Monday?

**Comment by waqadArshad** [comment]
> @Meherdeep could you take a look at this Monday?

@maxxfrazer @Meherdeep

Thanks for this I updated the agora versions and it got resolved. But I am now getting this following error quite often.

```
PlatformException(-17, request to join channel is rejected, null, null)
```

Agora version: 

```
agora_uikit: ^1.0.2
```

Here is my configuration:

```
final AgoraClient client = AgoraClient(
    agoraConnectionData: AgoraConnectionData(
      appId: "40216abc119348c4a6236c11ab1a0c3e",
      tokenUrl: "https://nikah----match.herokuapp.com",
      // tokenUrl: "https://nikah--match.herokuapp.com/access_token?",
      channelName: currentChannel,
      uid: 0,
      rtmEnabled: false,
    ),
    enabledPermission: [
      Permission.camera,
      Permission.microphone,
    ],
  );
```
using this in initState:

```
  void initAgora() async {
    log("Channel name before client.initialize() is: $channelName");
    try {
      await client.initialize();
    } catch (e) {
      showErrorDialog(
        title: "Error!",
        description: "Some unknown error was thrown while joining the call. Trying again.",
      );
      log("exceotion is: $e"); // this logs that above error.
      await client.initialize();
    }
  }

```

and my flutter doctor -v:

```
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1706], locale en-US)
    • Flutter version 2.10.5 at C:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (10 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\waqad\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\waqad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • RMX2030 (mobile)  • b37273eb • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 102.0.1245.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

Can you please have a look? I search for it but could understand what is causing this. It is really very annoying. Thanks for your time.
